import type { Language, Story, Business, Category, TranslationSet, Deal } from './types';
import { UtensilsCrossed, ShoppingBag, Sprout, Ticket, BedDouble, Landmark, Briefcase, Car, Building } from './components/IconComponents';

export const LANGUAGES: { code: Language; name: string }[] = [
  { code: 'en', name: 'English' },
  { code: 'ar', name: 'العربية' },
  { code: 'ku', name: 'کوردی' },
];

export const GOVERNORATES = [
  { id: 'all', labelKey: 'all' },
  { id: 'Baghdad', labelKey: 'baghdad' },
  { id: 'Erbil', labelKey: 'erbil' },
  { id: 'Basra', labelKey: 'basra' },
  { id: 'Slemani', labelKey: 'slemani' },
  { id: 'Duhok', labelKey: 'duhok' },
];

export const MOCK_STORIES: Story[] = [
  { id: 1, username: "BaghdadLife", avatarUrl: "https://picsum.photos/seed/s1/1080/1920" },
  { id: 2, username: "ErbilNights", avatarUrl: "https://picsum.photos/seed/s2/1080/1920" },
  { id: 3, username: "BasraVibes", avatarUrl: "https://picsum.photos/seed/s3/1080/1920" },
  { id: 4, username: "MosulArts", avatarUrl: "https://picsum.photos/seed/s4/1080/1920" },
  { id: 5, username: "KurdistanTravel", avatarUrl: "https://picsum.photos/seed/s5/1080/1920" },
  { id: 6, username: "IraqiFoodie", avatarUrl: "https://picsum.photos/seed/s6/1080/1920" },
  { id: 7, username: "SuliEvents", avatarUrl: "https://picsum.photos/seed/s7/1080/1920" },
];

export const CATEGORIES: Category[] = [
  { 
    id: 'food', 
    labelKey: 'food', 
    icon: UtensilsCrossed, 
    subcategories: [ 
        { id: 'dining_local', labelKey: 'dining_local' },
        { id: 'dining_international', labelKey: 'dining_international' },
        { id: 'dining_fine', labelKey: 'dining_fine' },
        { id: 'dining_casual', labelKey: 'dining_casual' },
        { id: 'dining_themed', labelKey: 'dining_themed' },
        { id: 'cafe_specialty', labelKey: 'cafe_specialty' },
        { id: 'cafe_tea_houses', labelKey: 'cafe_tea_houses' },
        { id: 'cafe_coworking', labelKey: 'cafe_coworking' },
        { id: 'cafe_dessert', labelKey: 'cafe_dessert' },
        { id: 'quick_service_trucks', labelKey: 'quick_service_trucks' },
        { id: 'quick_service_street', labelKey: 'quick_service_street' },
        { id: 'quick_service_fast_casual', labelKey: 'quick_service_fast_casual' },
        { id: 'quick_service_courts', labelKey: 'quick_service_courts' },
        { id: 'dietary_vegan', labelKey: 'dietary_vegan' },
        { id: 'dietary_halal', labelKey: 'dietary_halal' },
        { id: 'dietary_gluten_free', labelKey: 'dietary_gluten_free' },
        { id: 'dietary_healthy', labelKey: 'dietary_healthy' },
        { id: 'market_farmers', labelKey: 'market_farmers' },
        { id: 'market_specialty', labelKey: 'market_specialty' },
        { id: 'market_producers', labelKey: 'market_producers' },
    ] 
  },
  { 
    id: 'events', 
    labelKey: 'events', 
    icon: Ticket, 
    subcategories: [ 
      {id: 'events_live_concerts', labelKey: 'events_live_concerts'}, 
      {id: 'events_live_theater', labelKey: 'events_live_theater'}, 
      {id: 'events_live_dance', labelKey: 'events_live_dance'}, 
      {id: 'events_live_comedy', labelKey: 'events_live_comedy'},
      {id: 'events_festivals_cultural', labelKey: 'events_festivals_cultural'}, 
      {id: 'events_festivals_religious', labelKey: 'events_festivals_religious'}, 
      {id: 'events_festivals_seasonal', labelKey: 'events_festivals_seasonal'}, 
      {id: 'events_festivals_community', labelKey: 'events_festivals_community'},
      {id: 'events_media_theaters', labelKey: 'events_media_theaters'}, 
      {id: 'events_media_film_festivals', labelKey: 'events_media_film_festivals'}, 
      {id: 'events_media_gaming', labelKey: 'events_media_gaming'}, 
      {id: 'events_media_vr', labelKey: 'events_media_vr'},
      {id: 'events_social_lounges', labelKey: 'events_social_lounges'}, 
      {id: 'events_social_hookah', labelKey: 'events_social_hookah'}, 
      {id: 'events_social_clubs', labelKey: 'events_social_clubs'}, 
      {id: 'events_social_karaoke', labelKey: 'events_social_karaoke'},
      {id: 'events_sports_events', labelKey: 'events_sports_events'},
      {id: 'events_sports_fitness', labelKey: 'events_sports_fitness'},
      {id: 'events_sports_outdoor', labelKey: 'events_sports_outdoor'},
      {id: 'events_sports_spectator', labelKey: 'events_sports_spectator'},
    ] 
  },
  { id: 'hotels', labelKey: 'hotels', icon: BedDouble, subcategories: [ 
      {id: 'hotels_luxury', labelKey: 'hotels_luxury'}, 
      {id: 'hotels_business', labelKey: 'hotels_business'}, 
      {id: 'hotels_boutique', labelKey: 'hotels_boutique'}, 
      {id: 'hotels_resort', labelKey: 'hotels_resort'},
      {id: 'alternative_vacation', labelKey: 'alternative_vacation'}, 
      {id: 'alternative_guest_houses', labelKey: 'alternative_guest_houses'}, 
      {id: 'alternative_hostels', labelKey: 'alternative_hostels'}, 
      {id: 'alternative_homestays', labelKey: 'alternative_homestays'},
      {id: 'business_serviced_apartments', labelKey: 'business_serviced_apartments'}, 
      {id: 'business_coliving', labelKey: 'business_coliving'}, 
      {id: 'business_conference', labelKey: 'business_conference'}, 
      {id: 'business_corporate', labelKey: 'business_corporate'},
      {id: 'accessible_wheelchair', labelKey: 'accessible_wheelchair'}, 
      {id: 'accessible_family', labelKey: 'accessible_family'}, 
      {id: 'accessible_pet', labelKey: 'accessible_pet'}, 
      {id: 'accessible_senior', labelKey: 'accessible_senior'},
      {id: 'heritage_traditional', labelKey: 'heritage_traditional'}, 
      {id: 'heritage_hotels', labelKey: 'heritage_hotels'}, 
      {id: 'heritage_religious', labelKey: 'heritage_religious'}, 
      {id: 'heritage_eco_lodges', labelKey: 'heritage_eco_lodges'},
  ] },
  { id: 'shopping', labelKey: 'shopping', icon: ShoppingBag, subcategories: [ 
      {id: 'shopping_malls', labelKey: 'shopping_malls'}, 
      {id: 'shopping_department_stores', labelKey: 'shopping_department_stores'}, 
      {id: 'shopping_outlet_centers', labelKey: 'shopping_outlet_centers'}, 
      {id: 'shopping_retail_chains', labelKey: 'shopping_retail_chains'},
      {id: 'shopping_souqs', labelKey: 'shopping_souqs'}, 
      {id: 'shopping_farmers_markets', labelKey: 'shopping_farmers_markets'}, 
      {id: 'shopping_night_markets', labelKey: 'shopping_night_markets'}, 
      {id: 'shopping_flea_markets', labelKey: 'shopping_flea_markets'},
      {id: 'shopping_handicrafts', labelKey: 'shopping_handicrafts'}, 
      {id: 'shopping_antiques', labelKey: 'shopping_antiques'}, 
      {id: 'shopping_local_products', labelKey: 'shopping_local_products'}, 
      {id: 'shopping_artifacts', labelKey: 'shopping_artifacts'},
      {id: 'shopping_tailoring', labelKey: 'shopping_tailoring'}, 
      {id: 'shopping_electronics_repair', labelKey: 'shopping_electronics_repair'}, 
      {id: 'shopping_shoe_repair', labelKey: 'shopping_shoe_repair'}, 
      {id: 'shopping_custom_orders', labelKey: 'shopping_custom_orders'},
      {id: 'shopping_eco_friendly', labelKey: 'shopping_eco_friendly'}, 
      {id: 'shopping_local_producers', labelKey: 'shopping_local_producers'}, 
      {id: 'shopping_secondhand', labelKey: 'shopping_secondhand'}, 
      {id: 'shopping_fair_trade', labelKey: 'shopping_fair_trade'},
  ] },
  { id: 'tourism', labelKey: 'tourism', icon: Landmark, subcategories: [ 
      { id: 'historical_archaeological', labelKey: 'historical_archaeological' },
      { id: 'historical_monuments', labelKey: 'historical_monuments' },
      { id: 'historical_unesco', labelKey: 'historical_unesco' },
      { id: 'historical_ruins', labelKey: 'historical_ruins' },
      { id: 'museums_art', labelKey: 'museums_art' },
      { id: 'museums_historical', labelKey: 'museums_historical' },
      { id: 'museums_science', labelKey: 'museums_science' },
      { id: 'museums_cultural_centers', labelKey: 'museums_cultural_centers' },
      { id: 'learning_libraries', labelKey: 'learning_libraries' },
      { id: 'learning_workshops', labelKey: 'learning_workshops' },
      { id: 'learning_tours', labelKey: 'learning_tours' },
      { id: 'learning_educational_centers', labelKey: 'learning_educational_centers' },
      { id: 'religious_mosques', labelKey: 'religious_mosques' },
      { id: 'religious_churches', labelKey: 'religious_churches' },
      { id: 'religious_shrines', labelKey: 'religious_shrines' },
      { id: 'religious_centers', labelKey: 'religious_centers' },
      { id: 'public_parks', labelKey: 'public_parks' },
      { id: 'public_squares', labelKey: 'public_squares' },
      { id: 'public_waterfronts', labelKey: 'public_waterfronts' },
      // FIX: Renamed labelKey and id to avoid duplicate key conflict with 'emergency' category's subcategory.
      { id: 'tourism_public_community_centers', labelKey: 'tourism_public_community_centers' },
  ] },
  { id: 'business', labelKey: 'business', icon: Briefcase, subcategories: [ 
      {id: 'business_financial_banks', labelKey: 'business_financial_banks'}, 
      {id: 'business_financial_exchange', labelKey: 'business_financial_exchange'}, 
      {id: 'business_financial_atms', labelKey: 'business_financial_atms'}, 
      {id: 'business_financial_advisors', labelKey: 'business_financial_advisors'},
      {id: 'business_comm_mobile', labelKey: 'business_comm_mobile'}, 
      {id: 'business_comm_internet', labelKey: 'business_comm_internet'}, 
      {id: 'business_comm_postal', labelKey: 'business_comm_postal'}, 
      {id: 'business_comm_printing', labelKey: 'business_comm_printing'},
      {id: 'business_prof_legal', labelKey: 'business_prof_legal'}, 
      {id: 'business_prof_accounting', labelKey: 'business_prof_accounting'}, 
      {id: 'business_prof_centers', labelKey: 'business_prof_centers'}, 
      {id: 'business_prof_coworking', labelKey: 'business_prof_coworking'},
      {id: 'business_tech_it', labelKey: 'business_tech_it'}, 
      {id: 'business_tech_engineering', labelKey: 'business_tech_engineering'}, 
      {id: 'business_tech_repair', labelKey: 'business_tech_repair'}, 
      {id: 'business_tech_digital', labelKey: 'business_tech_digital'},
      {id: 'business_edu_tutoring', labelKey: 'business_edu_tutoring'}, 
      {id: 'business_edu_language', labelKey: 'business_edu_language'}, 
      {id: 'business_edu_vocational', labelKey: 'business_edu_vocational'}, 
      {id: 'business_edu_consultants', labelKey: 'business_edu_consultants'},
  ] },
  { id: 'health', labelKey: 'health', icon: Sprout, subcategories: [ 
      { id: 'health_medical_hospitals', labelKey: 'health_medical_hospitals' },
      { id: 'health_medical_clinics', labelKey: 'health_medical_clinics' },
      { id: 'health_medical_specialists', labelKey: 'health_medical_specialists' },
      { id: 'health_medical_emergency', labelKey: 'health_medical_emergency' },
      { id: 'health_pharmacies_24hr', labelKey: 'health_pharmacies_24hr' },
      { id: 'health_pharmacies_traditional', labelKey: 'health_pharmacies_traditional' },
      { id: 'health_pharmacies_supplies', labelKey: 'health_pharmacies_supplies' },
      { id: 'health_pharmacies_prescription', labelKey: 'health_pharmacies_prescription' },
      { id: 'health_wellness_gyms', labelKey: 'health_wellness_gyms' },
      { id: 'health_wellness_yoga', labelKey: 'health_wellness_yoga' },
      { id: 'health_wellness_spas', labelKey: 'health_wellness_spas' },
      { id: 'health_wellness_sports', labelKey: 'health_wellness_sports' },
      { id: 'health_mental_counseling', labelKey: 'health_mental_counseling' },
      { id: 'health_mental_support', labelKey: 'health_mental_support' },
      { id: 'health_mental_therapy', labelKey: 'health_mental_therapy' },
      { id: 'health_mental_retreats', labelKey: 'health_mental_retreats' },
      { id: 'health_family_pediatric', labelKey: 'health_family_pediatric' },
      { id: 'health_family_womens', labelKey: 'health_family_womens' },
      { id: 'health_family_senior', labelKey: 'health_family_senior' },
      { id: 'health_family_planning', labelKey: 'health_family_planning' },
  ] },
  { id: 'transport', labelKey: 'transport', icon: Car, subcategories: [ 
      {id: 'transport_local_taxi', labelKey: 'transport_local_taxi'},
      {id: 'transport_local_rideshare', labelKey: 'transport_local_rideshare'},
      {id: 'transport_local_bus', labelKey: 'transport_local_bus'},
      {id: 'transport_local_metro', labelKey: 'transport_local_metro'},
      {id: 'transport_vehicle_rentals', labelKey: 'transport_vehicle_rentals'},
      {id: 'transport_vehicle_repair', labelKey: 'transport_vehicle_repair'},
      {id: 'transport_vehicle_fuel', labelKey: 'transport_vehicle_fuel'},
      {id: 'transport_vehicle_parking', labelKey: 'transport_vehicle_parking'},
      {id: 'transport_travel_agencies', labelKey: 'transport_travel_agencies'},
      {id: 'transport_travel_airlines', labelKey: 'transport_travel_airlines'},
      {id: 'transport_travel_bus_terminals', labelKey: 'transport_travel_bus_terminals'},
      {id: 'transport_travel_train_stations', labelKey: 'transport_travel_train_stations'},
      {id: 'transport_accessible_wheelchair', labelKey: 'transport_accessible_wheelchair'},
      {id: 'transport_accessible_senior', labelKey: 'transport_accessible_senior'},
      {id: 'transport_accessible_family', labelKey: 'transport_accessible_family'},
      {id: 'transport_accessible_special', labelKey: 'transport_accessible_special'},
      {id: 'transport_alternative_bike', labelKey: 'transport_alternative_bike'},
      {id: 'transport_alternative_walking', labelKey: 'transport_alternative_walking'},
      {id: 'transport_alternative_scooter', labelKey: 'transport_alternative_scooter'},
      {id: 'transport_alternative_eco', labelKey: 'transport_alternative_eco'},
  ] },
  { 
    id: 'emergency', 
    labelKey: 'emergency', 
    icon: Building, 
    subcategories: [ 
        {id: 'public_gov_municipal', labelKey: 'public_gov_municipal'},
        {id: 'public_gov_police', labelKey: 'public_gov_police'},
        {id: 'public_gov_embassies', labelKey: 'public_gov_embassies'},
        {id: 'public_gov_records', labelKey: 'public_gov_records'},
        {id: 'public_emergency_numbers', labelKey: 'public_emergency_numbers'},
        {id: 'public_emergency_police', labelKey: 'public_emergency_police'},
        {id: 'public_emergency_fire', labelKey: 'public_emergency_fire'},
        {id: 'public_emergency_shelters', labelKey: 'public_emergency_shelters'},
        {id: 'public_community_centers', labelKey: 'public_community_centers'},
        {id: 'public_community_religious', labelKey: 'public_community_religious'},
        {id: 'public_community_ngos', labelKey: 'public_community_ngos'},
        {id: 'public_community_volunteer', labelKey: 'public_community_volunteer'},
        {id: 'public_facilities_restrooms', labelKey: 'public_facilities_restrooms'},
        {id: 'public_facilities_prayer', labelKey: 'public_facilities_prayer'},
        {id: 'public_facilities_water', labelKey: 'public_facilities_water'},
        {id: 'public_facilities_wifi', labelKey: 'public_facilities_wifi'},
        {id: 'public_tourist_info', labelKey: 'public_tourist_info'},
        {id: 'public_tourist_guides', labelKey: 'public_tourist_guides'},
        {id: 'public_tourist_translation', labelKey: 'public_tourist_translation'},
        {id: 'public_tourist_visa', labelKey: 'public_tourist_visa'},
    ] 
  },
];

export const MOCK_BUSINESSES: Business[] = [
  { id: 1, name: "Baghdad Mall", category: "shopping", imageUrl: "https://picsum.photos/seed/b1/400/300", governorate: "Baghdad", isAccessible: true, rating: 4.5, priceRange: 'mid', amenities: ['Free Wi-Fi', 'Parking', 'Food Court'] },
  { id: 2, name: "Shanidar Park", category: "tourism", imageUrl: "https://picsum.photos/seed/b2/400/300", governorate: "Erbil", isAccessible: false, rating: 4.8, priceRange: 'low', amenities: ['Gardens', 'Playground'] },
  { id: 3, name: "Times Square Basra", category: "events", imageUrl: "https://picsum.photos/seed/b3/400/300", governorate: "Basra", isAccessible: true, rating: 4.2, priceRange: 'mid', amenities: ['Cinema', 'Restaurants', 'Shops'] },
  { id: 4, name: "Family Mall", category: "shopping", imageUrl: "https://picsum.photos/seed/b4/400/300", governorate: "Slemani", isAccessible: true, rating: 4.6, priceRange: 'mid', amenities: ['Supermarket', 'Fashion', 'Cafe'] },
  { id: 5, name: "Divan Erbil", category: "hotels", imageUrl: "https://picsum.photos/seed/b5/400/300", governorate: "Erbil", isAccessible: true, rating: 5.0, priceRange: 'high', amenities: ['Pool', 'Spa', 'Gym', 'Fine Dining'] },
  { id: 6, name: "The Station", category: "business", imageUrl: "https://picsum.photos/seed/b6/400/300", governorate: "Baghdad", isAccessible: false, rating: 4.9, priceRange: 'mid', amenities: ['High-speed Wi-Fi', 'Meeting Rooms'] },
  { id: 7, name: "Khan Murjan", category: "food", imageUrl: "https://picsum.photos/seed/b7/400/300", governorate: "Baghdad", isAccessible: false, rating: 4.7, priceRange: 'high', amenities: ['Traditional Iraqi Cuisine', 'Historic Building'] },
  { id: 8, name: "Gali Ali Bag Waterfall", category: "tourism", imageUrl: "https://picsum.photos/seed/b8/400/300", governorate: "Erbil", isAccessible: false, rating: 4.8, priceRange: 'low', amenities: ['Nature', 'Scenery', 'Restaurants'] },
  { id: 9, name: "Amna Suraka Museum", category: "tourism", imageUrl: "https://picsum.photos/seed/b9/400/300", governorate: "Slemani", isAccessible: true, rating: 4.5, priceRange: 'low', amenities: ['Historic Site', 'Exhibits'] },
  { id: 10, name: "Duhok Mall", category: "shopping", imageUrl: "https://picsum.photos/seed/b10/400/300", governorate: "Duhok", isAccessible: true, rating: 4.3, priceRange: 'mid', amenities: ['Parking', 'Food Court'] },
  { id: 11, name: "Majidi Land", category: "events", imageUrl: "https://picsum.photos/seed/b11/400/300", governorate: "Erbil", isAccessible: false, rating: 4.1, priceRange: 'mid', amenities: ['Amusement Park', 'Rides'] },
  { id: 12, name: "Basra International Hotel", category: "hotels", imageUrl: "https://picsum.photos/seed/b12/400/300", governorate: "Basra", isAccessible: true, rating: 4.6, priceRange: 'high', amenities: ['Pool', 'Gym', 'Conference Rooms'] },
];

const now = new Date();
export const MOCK_DEALS: Deal[] = [
    { id: 1, businessName: "Pizza Royal", title: "50% Off Any Large Pizza", imageUrl: "https://picsum.photos/seed/d1/400/300", originalPrice: 20000, discountedPrice: 10000, claimed: 45, total: 100, expiresAt: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000), governorate: "Baghdad" },
    { id: 2, businessName: "Erbil Rotana", title: "Weekend Getaway Package", imageUrl: "https://picsum.photos/seed/d2/400/300", originalPrice: 250000, discountedPrice: 175000, claimed: 12, total: 20, expiresAt: new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000), governorate: "Erbil" },
    { id: 3, businessName: "City Centre Basra", title: "Free Popcorn with Movie Ticket", imageUrl: "https://picsum.photos/seed/d3/400/300", originalPrice: 5000, discountedPrice: 0, claimed: 250, total: 500, expiresAt: new Date(now.getTime() + 1 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000), governorate: "Basra" },
    { id: 4, businessName: "Suli Grand Spa", title: "30% Off Massage Therapy", imageUrl: "https://picsum.photos/seed/d4/400/300", originalPrice: 75000, discountedPrice: 52500, claimed: 30, total: 50, expiresAt: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000), governorate: "Slemani" },
    { id: 5, businessName: "Baghdad Bowling", title: "Buy One Game, Get One Free", imageUrl: "https://picsum.photos/seed/d5/400/300", originalPrice: 10000, discountedPrice: 5000, claimed: 150, total: 200, expiresAt: new Date(now.getTime() + 0.5 * 24 * 60 * 60 * 1000), governorate: "Baghdad" },
    { id: 6, businessName: "Kurdistan Books", title: "20% Off All English Books", imageUrl: "https://picsum.photos/seed/d6/400/300", originalPrice: 30000, discountedPrice: 24000, claimed: 88, total: 120, expiresAt: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000), governorate: "Erbil" },
];


export const TRANSLATIONS: Record<Language, TranslationSet> = {
  en: {
    header: {
      home: "Home",
      explore: "Explore",
      businesses: "Businesses",
      deals: "Deals",
      login: "Login"
    },
    hero: {
      mainTitle: "Discover Events Across Iraq & Kurdistan",
      searchPlaceholder: "Ask our AI... 'what are the best concerts in Erbil this month?'",
      searchButton: "Search",
      voiceSearchTooltip: "Search by voice",
      listening: "Listening...",
      filterByGovernorate: "Filter by Governorate"
    },
    governorates: {
      all: "All Governorates",
      baghdad: "Baghdad",
      erbil: "Erbil",
      basra: "Basra",
      slemani: "Slemani",
      duhok: "Duhok"
    },
    categories: {
      food: "Dining & Cuisine",
      events: "Entertainment & Events",
      hotels: "Accommodation & Stays",
      shopping: "Shopping & Retail",
      tourism: "Culture & Heritage",
      business: "Business & Services",
      health: "Health & Wellness",
      transport: "Transport & Mobility",
      emergency: "Public & Essential",
    },
    subcategories: {
        dining_local: 'Local & Traditional',
        dining_international: 'International Cuisine',
        dining_fine: 'Fine Dining',
        dining_casual: 'Casual & Family',
        dining_themed: 'Themed Experiences',
        cafe_specialty: 'Specialty Coffee',
        cafe_tea_houses: 'Traditional Tea Houses',
        cafe_coworking: 'Co-working Cafes',
        cafe_dessert: 'Dessert & Pastry',
        quick_service_trucks: 'Food Trucks',
        quick_service_street: 'Street Food Stalls',
        quick_service_fast_casual: 'Fast Casual',
        quick_service_courts: 'Food Courts',
        dietary_vegan: 'Vegetarian & Vegan',
        dietary_halal: 'Halal Certified',
        dietary_gluten_free: 'Gluten-Free Options',
        dietary_healthy: 'Healthy & Organic',
        market_farmers: 'Farmers Markets',
        market_specialty: 'Specialty Food Stores',
        market_producers: 'Local Producers',

        events_live_concerts: 'Music Concerts',
        events_live_theater: 'Theater & Drama',
        events_live_dance: 'Dance Performances',
        events_live_comedy: 'Comedy Shows',
        events_festivals_cultural: 'Cultural Festivals',
        events_festivals_religious: 'Religious Celebrations',
        events_festivals_seasonal: 'Seasonal Events',
        events_festivals_community: 'Community Gatherings',
        events_media_theaters: 'Movie Theaters',
        events_media_film_festivals: 'Film Festivals',
        events_media_gaming: 'Gaming Centers',
        events_media_vr: 'Virtual Reality',
        events_social_lounges: 'Lounges & Bars',
        events_social_hookah: 'Hookah Cafes',
        events_social_clubs: 'Social Clubs',
        events_social_karaoke: 'Karaoke & Games',
        events_sports_events: 'Sports Events',
        events_sports_fitness: 'Fitness Classes',
        events_sports_outdoor: 'Outdoor Activities',
        events_sports_spectator: 'Spectator Sports',

        hotels_luxury: 'Luxury & 5-Star',
        hotels_business: 'Business Hotels',
        hotels_boutique: 'Boutique Hotels',
        hotels_resort: 'Resort Complexes',
        alternative_vacation: 'Vacation Rentals',
        alternative_guest_houses: 'Guest Houses',
        alternative_hostels: 'Hostels',
        alternative_homestays: 'Homestays',
        business_serviced_apartments: 'Serviced Apartments',
        business_coliving: 'Co-living Spaces',
        business_conference: 'Conference Hotels',
        business_corporate: 'Corporate Housing',
        accessible_wheelchair: 'Wheelchair Accessible',
        accessible_family: 'Family-Friendly',
        accessible_pet: 'Pet-Friendly',
        accessible_senior: 'Senior-Friendly',
        heritage_traditional: 'Traditional Houses',
        heritage_hotels: 'Heritage Hotels',
        heritage_religious: 'Religious Stays',
        heritage_eco_lodges: 'Eco-Lodges',

        shopping_malls: 'Shopping Malls',
        shopping_department_stores: 'Department Stores',
        shopping_outlet_centers: 'Outlet Centers',
        shopping_retail_chains: 'Retail Chains',
        shopping_souqs: 'Traditional Souqs',
        shopping_farmers_markets: 'Farmers Markets',
        shopping_night_markets: 'Night Markets',
        shopping_flea_markets: 'Flea Markets',
        shopping_handicrafts: 'Handicrafts & Artisans',
        shopping_antiques: 'Antiques & Collectibles',
        shopping_local_products: 'Local Products',
        shopping_artifacts: 'Cultural Artifacts',
        shopping_tailoring: 'Tailoring & Alterations',
        shopping_electronics_repair: 'Electronics Repair',
        shopping_shoe_repair: 'Shoe & Leather Repair',
        shopping_custom_orders: 'Custom Orders',
        shopping_eco_friendly: 'Eco-Friendly Products',
        shopping_local_producers: 'Local Producers',
        shopping_secondhand: 'Secondhand & Vintage',
        shopping_fair_trade: 'Fair Trade',
        
        historical_archaeological: 'Archaeological Sites',
        historical_monuments: 'Historical Monuments',
        historical_unesco: 'UNESCO Heritage',
        historical_ruins: 'Ancient Ruins',
        museums_art: 'Art Museums',
        museums_historical: 'Historical Museums',
        museums_science: 'Science & Technology',
        museums_cultural_centers: 'Cultural Centers',
        learning_libraries: 'Libraries',
        learning_workshops: 'Workshops & Classes',
        learning_tours: 'Cultural Tours',
        learning_educational_centers: 'Educational Centers',
        religious_mosques: 'Mosques',
        religious_churches: 'Churches',
        religious_shrines: 'Shrines',
        religious_centers: 'Religious Centers',
        public_parks: 'Parks & Gardens',
        public_squares: 'Public Squares',
        public_waterfronts: 'Waterfronts',
        // FIX: Renamed key to 'tourism_public_community_centers' to avoid duplicate key error.
        tourism_public_community_centers: 'Community Centers',

        business_financial_banks: 'Banks',
        business_financial_exchange: 'Currency Exchange',
        business_financial_atms: 'ATMs',
        business_financial_advisors: 'Financial Advisors',
        business_comm_mobile: 'Mobile Providers',
        business_comm_internet: 'Internet Services',
        business_comm_postal: 'Postal Services',
        business_comm_printing: 'Printing & Copying',
        business_prof_legal: 'Legal Services',
        business_prof_accounting: 'Accounting & Tax',
        business_prof_centers: 'Business Centers',
        business_prof_coworking: 'Co-working Spaces',
        business_tech_it: 'IT Support',
        business_tech_engineering: 'Engineering Services',
        business_tech_repair: 'Technical Repair',
        business_tech_digital: 'Digital Services',
        business_edu_tutoring: 'Tutoring Centers',
        business_edu_language: 'Language Schools',
        business_edu_vocational: 'Vocational Training',
        business_edu_consultants: 'Educational Consultants',

        health_medical_hospitals: 'Hospitals',
        health_medical_clinics: 'Clinics',
        health_medical_specialists: 'Specialists',
        health_medical_emergency: 'Emergency Care',
        health_pharmacies_24hr: '24-Hour Pharmacies',
        health_pharmacies_traditional: 'Traditional Medicine',
        health_pharmacies_supplies: 'Medical Supplies',
        health_pharmacies_prescription: 'Prescription Services',
        health_wellness_gyms: 'Gyms & Fitness Centers',
        health_wellness_yoga: 'Yoga & Meditation',
        health_wellness_spas: 'Spas & Wellness Centers',
        health_wellness_sports: 'Sports Facilities',
        health_mental_counseling: 'Counseling Services',
        health_mental_support: 'Support Groups',
        health_mental_therapy: 'Therapy Centers',
        health_mental_retreats: 'Wellness Retreats',
        health_family_pediatric: 'Pediatric Care',
        health_family_womens: 'Women\'s Health',
        health_family_senior: 'Senior Care',
        health_family_planning: 'Family Planning',

        transport_local_taxi: 'Taxi Services',
        transport_local_rideshare: 'Ride Sharing',
        transport_local_bus: 'Public Buses',
        transport_local_metro: 'Metro & Trains',
        transport_vehicle_rentals: 'Car Rentals',
        transport_vehicle_repair: 'Vehicle Repair',
        transport_vehicle_fuel: 'Fuel Stations',
        transport_vehicle_parking: 'Parking Facilities',
        transport_travel_agencies: 'Travel Agencies',
        transport_travel_airlines: 'Airline Offices',
        transport_travel_bus_terminals: 'Bus Terminals',
        transport_travel_train_stations: 'Train Stations',
        transport_accessible_wheelchair: 'Wheelchair Accessible',
        transport_accessible_senior: 'Senior Transport',
        transport_accessible_family: 'Family Transport',
        transport_accessible_special: 'Special Needs Services',
        transport_alternative_bike: 'Bicycle Rentals',
        transport_alternative_walking: 'Walking Routes',
        transport_alternative_scooter: 'Scooter Services',
        transport_alternative_eco: 'Eco-Transport',
        
        public_gov_municipal: 'Municipal Offices',
        public_gov_police: 'Police Stations',
        public_gov_embassies: 'Embassies & Consulates',
        public_gov_records: 'Public Records',
        public_emergency_numbers: 'Emergency Numbers',
        public_emergency_police: 'Police Stations',
        public_emergency_fire: 'Fire Departments',
        public_emergency_shelters: 'Emergency Shelters',
        public_community_centers: 'Community Centers',
        public_community_religious: 'Religious Centers',
        public_community_ngos: 'NGOs & Charities',
        public_community_volunteer: 'Volunteer Opportunities',
        public_facilities_restrooms: 'Public Restrooms',
        public_facilities_prayer: 'Prayer Rooms',
        public_facilities_water: 'Drinking Water',
        public_facilities_wifi: 'Public Wi-Fi Zones',
        public_tourist_info: 'Information Centers',
        public_tourist_guides: 'Tour Guides',
        public_tourist_translation: 'Translation Services',
        public_tourist_visa: 'Visa & Immigration',
    },
    categoryModal: {
      title: 'Explore',
      allCategory: 'All {category}'
    },
    featuredBusinesses: {
      title: "Featured Businesses & Venues"
    },
    curatedEvents: {
      title: "AI Curated Events For You",
      description: "Let our AI generate unique event ideas based on your interests. Click the button to get started!",
      generateButton: "Generate Event Ideas",
      generating: "Our AI is thinking...",
      error: "Sorry, something went wrong. Please try again.",
      aiCurated: "AI Curated",
    },
    dealsMarketplace: {
        title: "Deals Marketplace",
        claimed: "Claimed",
        expiresIn: "Expires in",
        days: "d",
        hours: "h",
        minutes: "m",
        seconds: "s",
    },
    businessDirectory: {
        title: "Business Directory",
        searchPlaceholder: "Search by business name...",
        filterByGovernorate: "Filter by Governorate",
        filterByCategory: "Filter by Category",
        filterByPrice: "Price Range",
        filterByRating: "Rating",
        sortBy: "Sort By",
        allGovernorates: "All Governorates",
        allCategories: "All Categories",
        priceAll: "Any Price",
        priceLow: "Affordable",
        priceMid: "Mid-Range",
        priceHigh: "Luxury",
        ratingAll: "Any Rating",
        sortDefault: "Default",
        sortNameAsc: "Name (A-Z)",
        sortRatingDesc: "Rating (High-Low)",
        resetFilters: "Reset",
        noResults: "No businesses found matching your criteria."
    },
    storyViewer: {
        close: "Close story viewer",
        next: "Next story",
        previous: "Previous story"
    },
    cityNavigator: {
        title: "City Navigator",
        description: "Explore cities, find points of interest, and plan your journey with our upcoming interactive map.",
        searchPlaceholder: "Search for a city or place...",
        planJourneyButton: "Plan Journey"
    },
    accessibilityHub: {
        title: "Accessibility Hub",
        description: "We are committed to making Iraq Compass accessible to everyone. Customize your experience below.",
        settingsTitle: "Display Settings",
        fontSize: "Font Size",
        fontSizeSmall: "Small",
        fontSizeDefault: "Default",
        fontSizeLarge: "Large",
        reduceMotion: "Reduce Motion",
        motionEnabled: "Enabled",
        motionReduced: "Reduced",
        findInclusiveEventsTitle: "Find Inclusive Venues",
        accessibleVenue: "Accessible Venue"
    }
  },
  ar: {
    header: {
      home: "الرئيسية",
      explore: "استكشف",
      businesses: "الأعمال",
      deals: "العروض",
      login: "تسجيل الدخول"
    },
    hero: {
      mainTitle: "اكتشف الفعاليات في جميع أنحاء العراق وكردستان",
      searchPlaceholder: "اسأل الذكاء الاصطناعي... 'ما هي أفضل الحفلات في أربيل هذا الشهر؟'",
      searchButton: "بحث",
      voiceSearchTooltip: "البحث بالصوت",
      listening: "يستمع...",
      filterByGovernorate: "تصفية حسب المحافظة"
    },
    governorates: {
      all: "كل المحافظات",
      baghdad: "بغداد",
      erbil: "أربيل",
      basra: "البصرة",
      slemani: "السليمانية",
      duhok: "دهوك"
    },
    categories: {
      food: "طعام ومأكولات",
      events: "ترفيه وفعاليات",
      hotels: "إقامة وفنادق",
      shopping: "تسوق وتجزئة",
      tourism: "ثقافة وتراث",
      business: "أعمال وخدمات",
      health: "صحة وعافية",
      transport: "نقل وتنقل",
      emergency: "خدمات عامة وأساسية",
    },
    subcategories: {
        dining_local: 'محلي وتقليدي',
        dining_international: 'مطبخ عالمي',
        dining_fine: 'فاخر',
        dining_casual: 'عائلي',
        dining_themed: 'تجارب ذات طابع خاص',
        cafe_specialty: 'قهوة مختصة',
        cafe_tea_houses: 'مقاهي شاي تقليدية',
        cafe_coworking: 'مقاهي للعمل',
        cafe_dessert: 'حلويات ومعجنات',
        quick_service_trucks: 'عربات طعام',
        quick_service_street: 'أكشاك طعام الشارع',
        quick_service_fast_casual: 'وجبات سريعة راقية',
        quick_service_courts: 'ردهات الطعام',
        dietary_vegan: 'نباتي',
        dietary_halal: 'حلال معتمد',
        dietary_gluten_free: 'خالي من الغلوتين',
        dietary_healthy: 'صحي وعضوي',
        market_farmers: 'أسواق المزارعين',
        market_specialty: 'متاجر أغذية متخصصة',
        market_producers: 'منتجون محليون',

        events_live_concerts: 'حفلات موسيقية',
        events_live_theater: 'مسرح ودراما',
        events_live_dance: 'عروض رقص',
        events_live_comedy: 'عروض كوميدية',
        events_festivals_cultural: 'مهرجانات ثقافية',
        events_festivals_religious: 'احتفالات دينية',
        events_festivals_seasonal: 'فعاليات موسمية',
        events_festivals_community: 'تجمعات مجتمعية',
        events_media_theaters: 'دور سينما',
        events_media_film_festivals: 'مهرجانات أفلام',
        events_media_gaming: 'مراكز ألعاب',
        events_media_vr: 'واقع افتراضي',
        events_social_lounges: 'استراحات وبارات',
        events_social_hookah: 'مقاهي أرجيلة',
        events_social_clubs: 'نواد اجتماعية',
        events_social_karaoke: 'كاريوكي وألعاب',
        events_sports_events: 'أحداث رياضية',
        events_sports_fitness: 'حصص لياقة',
        events_sports_outdoor: 'أنشطة خارجية',
        events_sports_spectator: 'رياضات جماهيرية',

        hotels_luxury: 'فنادق فاخرة و5 نجوم',
        hotels_business: 'فنادق أعمال',
        hotels_boutique: 'فنادق بوتيك',
        hotels_resort: 'مجمعات منتجعات',
        alternative_vacation: 'إيجارات العطلات',
        alternative_guest_houses: 'بيوت ضيافة',
        alternative_hostels: 'نُزل',
        alternative_homestays: 'إقامة منزلية',
        business_serviced_apartments: 'شقق فندقية',
        business_coliving: 'مساحات معيشة مشتركة',
        business_conference: 'فنادق مؤتمرات',
        business_corporate: 'سكن الشركات',
        accessible_wheelchair: 'متاح للكراسي المتحركة',
        accessible_family: 'مناسب للعائلات',
        accessible_pet: 'صديق للحيوانات الأليفة',
        accessible_senior: 'مناسب لكبار السن',
        heritage_traditional: 'بيوت تقليدية',
        heritage_hotels: 'فنادق تراثية',
        heritage_religious: 'إقامات دينية',
        heritage_eco_lodges: 'نُزل بيئية',

        shopping_malls: 'مراكز تسوق',
        shopping_department_stores: 'متاجر كبرى',
        shopping_outlet_centers: 'مراكز أوتلت',
        shopping_retail_chains: 'سلاسل متاجر',
        shopping_souqs: 'أسواق تقليدية',
        shopping_farmers_markets: 'أسواق المزارعين',
        shopping_night_markets: 'أسواق ليلية',
        shopping_flea_markets: 'أسواق مستعمل',
        shopping_handicrafts: 'حرف يدوية وفنانون',
        shopping_antiques: 'تحف ومقتنيات',
        shopping_local_products: 'منتجات محلية',
        shopping_artifacts: 'قطع أثرية ثقافية',
        shopping_tailoring: 'خياطة وتعديلات',
        shopping_electronics_repair: 'تصليح إلكترونيات',
        shopping_shoe_repair: 'تصليح أحذية وجلود',
        shopping_custom_orders: 'طلبات مخصصة',
        shopping_eco_friendly: 'منتجات صديقة للبيئة',
        shopping_local_producers: 'منتجون محليون',
        shopping_secondhand: 'مستعمل وعتيق',
        shopping_fair_trade: 'تجارة عادلة',

        historical_archaeological: 'مواقع أثرية',
        historical_monuments: 'معالم تاريخية',
        historical_unesco: 'تراث اليونسكو',
        historical_ruins: 'أطلال قديمة',
        museums_art: 'متاحف الفن',
        museums_historical: 'متاحف تاريخية',
        museums_science: 'علوم وتكنولوجيا',
        museums_cultural_centers: 'مراكز ثقافية',
        learning_libraries: 'مكتبات',
        learning_workshops: 'ورش عمل ودروس',
        learning_tours: 'جولات ثقافية',
        learning_educational_centers: 'مراكز تعليمية',
        religious_mosques: 'مساجد',
        religious_churches: 'كنائس',
        religious_shrines: 'مزارات',
        religious_centers: 'مراكز دينية',
        public_parks: 'حدائق ومنتزهات',
        public_squares: 'ساحات عامة',
        public_waterfronts: 'واجهات بحرية',
        // FIX: Renamed key to 'tourism_public_community_centers' to avoid duplicate key error.
        tourism_public_community_centers: 'مراكز مجتمعية',

        business_financial_banks: 'بنوك',
        business_financial_exchange: 'صرافة',
        business_financial_atms: 'صرافات آلية',
        business_financial_advisors: 'مستشارون ماليون',
        business_comm_mobile: 'شركات اتصالات',
        business_comm_internet: 'خدمات الإنترنت',
        business_comm_postal: 'خدمات بريدية',
        business_comm_printing: 'طباعة وتصوير',
        business_prof_legal: 'خدمات قانونية',
        business_prof_accounting: 'محاسبة وضرائب',
        business_prof_centers: 'مراكز أعمال',
        business_prof_coworking: 'مساحات عمل مشتركة',
        business_tech_it: 'دعم فني',
        business_tech_engineering: 'خدمات هندسية',
        business_tech_repair: 'تصليح فني',
        business_tech_digital: 'خدمات رقمية',
        business_edu_tutoring: 'مراكز دروس خصوصية',
        business_edu_language: 'مدارس لغات',
        business_edu_vocational: 'تدريب مهني',
        business_edu_consultants: 'استشارات تعليمية',
        
        health_medical_hospitals: 'مستشفيات',
        health_medical_clinics: 'عيادات',
        health_medical_specialists: 'أخصائيون',
        health_medical_emergency: 'رعاية طارئة',
        health_pharmacies_24hr: 'صيدليات 24 ساعة',
        health_pharmacies_traditional: 'طب تقليدي',
        health_pharmacies_supplies: 'لوازم طبية',
        health_pharmacies_prescription: 'خدمات وصفات طبية',
        health_wellness_gyms: 'صالات رياضية ومراكز لياقة',
        health_wellness_yoga: 'يوغا وتأمل',
        health_wellness_spas: 'منتجعات صحية ومراكز عافية',
        health_wellness_sports: 'مرافق رياضية',
        health_mental_counseling: 'خدمات استشارية',
        health_mental_support: 'مجموعات دعم',
        health_mental_therapy: 'مراكز علاجية',
        health_mental_retreats: 'منتجعات صحية',
        health_family_pediatric: 'رعاية الأطفال',
        health_family_womens: 'صحة المرأة',
        health_family_senior: 'رعاية كبار السن',
        health_family_planning: 'تنظيم الأسرة',

        transport_local_taxi: 'خدمات سيارات الأجرة',
        transport_local_rideshare: 'مشاركة الركوب',
        transport_local_bus: 'حافلات عامة',
        transport_local_metro: 'مترو وقطارات',
        transport_vehicle_rentals: 'تأجير سيارات',
        transport_vehicle_repair: 'تصليح مركبات',
        transport_vehicle_fuel: 'محطات وقود',
        transport_vehicle_parking: 'مواقف سيارات',
        transport_travel_agencies: 'وكالات سفر',
        transport_travel_airlines: 'مكاتب طيران',
        transport_travel_bus_terminals: 'محطات حافلات',
        transport_travel_train_stations: 'محطات قطار',
        transport_accessible_wheelchair: 'متاح للكراسي المتحركة',
        transport_accessible_senior: 'نقل كبار السن',
        transport_accessible_family: 'نقل عائلي',
        transport_accessible_special: 'خدمات ذوي الاحتياجات الخاصة',
        transport_alternative_bike: 'تأجير دراجات',
        transport_alternative_walking: 'مسارات مشي',
        transport_alternative_scooter: 'خدمات سكوتر',
        transport_alternative_eco: 'نقل صديق للبيئة',

        public_gov_municipal: 'مكاتب البلدية',
        public_gov_police: 'مراكز الشرطة',
        public_gov_embassies: 'السفارات والقنصليات',
        public_gov_records: 'السجلات العامة',
        public_emergency_numbers: 'أرقام الطوارئ',
        public_emergency_police: 'مراكز الشرطة',
        public_emergency_fire: 'إدارات الإطفاء',
        public_emergency_shelters: 'ملاجئ الطوارئ',
        public_community_centers: 'المراكز المجتمعية',
        public_community_religious: 'المراكز الدينية',
        public_community_ngos: 'المنظمات غير الحكومية والجمعيات الخيرية',
        public_community_volunteer: 'فرص التطوع',
        public_facilities_restrooms: 'دورات المياه العامة',
        public_facilities_prayer: 'غرف الصلاة',
        public_facilities_water: 'مياه الشرب',
        public_facilities_wifi: 'مناطق واي فاي عامة',
        public_tourist_info: 'مراكز المعلومات',
        public_tourist_guides: 'مرشدون سياحيون',
        public_tourist_translation: 'خدمات الترجمة',
        public_tourist_visa: 'التأشيرات والهجرة',
    },
    categoryModal: {
      title: 'استكشف',
      allCategory: 'كل {category}'
    },
    featuredBusinesses: {
      title: "أعمال وأماكن مميزة"
    },
    curatedEvents: {
      title: "فعاليات منسقة بالذكاء الاصطناعي لك",
      description: "دع الذكاء الاصطناعي الخاص بنا يولد أفكارًا فريدة للفعاليات بناءً على اهتماماتك. انقر على الزر للبدء!",
      generateButton: "توليد أفكار فعاليات",
      generating: "الذكاء الاصطناعي يفكر...",
      error: "عذراً، حدث خطأ ما. يرجى المحاولة مرة أخرى.",
      aiCurated: "بواسطة AI",
    },
    dealsMarketplace: {
        title: "سوق العروض",
        claimed: "تم الحجز",
        expiresIn: "ينتهي في",
        days: "ي",
        hours: "س",
        minutes: "د",
        seconds: "ث",
    },
    businessDirectory: {
        title: "دليل الأعمال",
        searchPlaceholder: "ابحث باسم العمل...",
        filterByGovernorate: "تصفية حسب المحافظة",
        filterByCategory: "تصفية حسب الفئة",
        filterByPrice: "نطاق السعر",
        filterByRating: "التقييم",
        sortBy: "ترتيب حسب",
        allGovernorates: "كل المحافظات",
        allCategories: "كل الفئات",
        priceAll: "أي سعر",
        priceLow: "معقول",
        priceMid: "متوسط",
        priceHigh: "فاخر",
        ratingAll: "أي تقييم",
        sortDefault: "افتراضي",
        sortNameAsc: "الاسم (أ-ي)",
        sortRatingDesc: "التقييم (عالي-منخفض)",
        resetFilters: "إعادة تعيين",
        noResults: "لم يتم العثور على أعمال تطابق معاييرك."
    },
    storyViewer: {
        close: "إغلاق عارض القصة",
        next: "القصة التالية",
        previous: "القصة السابقة"
    },
    cityNavigator: {
        title: "ملاح المدينة",
        description: "استكشف المدن، واعثر على نقاط الاهتمام، وخطط لرحلتك باستخدام خريطتنا التفاعلية القادمة.",
        searchPlaceholder: "ابحث عن مدينة أو مكان...",
        planJourneyButton: "خطط لرحلة"
    },
    accessibilityHub: {
        title: "مركز الوصول",
        description: "نحن ملتزمون بجعل عراق كومباس متاحًا للجميع. خصص تجربتك أدناه.",
        settingsTitle: "إعدادات العرض",
        fontSize: "حجم الخط",
        fontSizeSmall: "صغير",
        fontSizeDefault: "افتراضي",
        fontSizeLarge: "كبير",
        reduceMotion: "تقليل الحركة",
        motionEnabled: "مفعل",
        motionReduced: "مخفض",
        findInclusiveEventsTitle: "البحث عن أماكن شاملة",
        accessibleVenue: "مكان متاح للجميع"
    }
  },
  ku: {
    header: {
      home: "سەرەکی",
      explore: "گەڕان",
      businesses: "بازرگانیەکان",
      deals: "داشکانەکان",
      login: "چوونەژوورەوە"
    },
    hero: {
      mainTitle: "ئیڤێنتەکان بدۆزەرەوە لە سەرتاسەری عێراق و کوردستان",
      searchPlaceholder: "پرسیار لە زیرەکی دەستکرد بکە... 'باشترین کۆنسێرتەکانی هەولێر چین ئەم مانگە؟'",
      searchButton: "گەڕان",
      voiceSearchTooltip: "بە دەنگ بگەڕێ",
      listening: "گوێگرتن...",
      filterByGovernorate: "فلتەر بەپێی پارێзگا"
    },
    governorates: {
      all: "هەموو پارێزگاکان",
      baghdad: "بەغداد",
      erbil: "هەولێر",
      basra: "بەسرە",
      slemani: "سلێمانی",
      duhok: "دهۆک"
    },
    categories: {
      food: "خواردن و چێشت",
      events: "کات بەسەربردن و ئیڤێنت",
      hotels: "شوێنی مانەوە و هۆتێل",
      shopping: "بازاڕکردن و فرۆشتن",
      tourism: "کەلتور و میرات",
      business: "کار و خزمەتگوزاری",
      health: "تەندروستی و لەشجوانی",
      transport: "گواستنەوە و هاتوچۆ",
      emergency: "گشتی و پێویست",
    },
     subcategories: {
        dining_local: 'خۆماڵی و نەریتی',
        dining_international: 'خواردنی نێودەوڵەتی',
        dining_fine: 'شاهانە',
        dining_casual: 'خێزانی',
        dining_themed: 'تایبەتمەند',
        cafe_specialty: 'قاوەی تایبət',
        cafe_tea_houses: 'چایخانەی نەریتی',
        cafe_coworking: 'کافێی کارکردن',
        cafe_dessert: 'شیرینی و کێک',
        quick_service_trucks: 'عەرەبانەی خواردن',
        quick_service_street: 'خواردنی سەرشەقام',
        quick_service_fast_casual: 'خواردنی خێرای کوالێتی باش',
        quick_service_courts: 'گۆڕەپانی خواردن',
        dietary_vegan: 'ڕووەکی',
        dietary_halal: 'حەڵاڵ',
        dietary_gluten_free: 'بێ گلوتین',
        dietary_healthy: 'تەندروست و ئۆرگانیک',
        market_farmers: 'بازاڕی جوتیاران',
        market_specialty: 'فرۆشگای خۆراکی تایبەت',
        market_producers: 'بەرهەمهێنەرە خۆماڵییەکان',
        
        events_live_concerts: 'کۆنسێرتی مۆسیقا',
        events_live_theater: 'شانۆ و دراما',
        events_live_dance: 'نمایشی سەما',
        events_live_comedy: 'نمایشی کۆمیدی',
        events_festivals_cultural: 'فیستیڤاڵی کلتوری',
        events_festivals_religious: 'بۆنە ئاینییەکان',
        events_festivals_seasonal: 'بۆنە وەرزییەکان',
        events_festivals_community: 'کۆبوونەوەی کۆمەڵایەتی',
        events_media_theaters: 'سینەماکان',
        events_media_film_festivals: 'فیستیڤاڵی فیلم',
        events_media_gaming: 'ناوەندی یاری',
        events_media_vr: 'واقیعی خەیاڵی',
        events_social_lounges: 'لاونج و باڕەکان',
        events_social_hookah: 'کافێی نێرگەلە',
        events_social_clubs: 'یانە کۆمەڵایەتییەکان',
        events_social_karaoke: 'کاریۆکی و یاری',
        events_sports_events: 'ڕووداوی وه‌رزشی',
        events_sports_fitness: 'کلاسەکانی لەشجوانی',
        events_sports_outdoor: 'چالاکی دەرەوە',
        events_sports_spectator: 'وه‌رزشی بینەران',

        hotels_luxury: 'هۆتێلی شاهانە و ٥ ئەستێرە',
        hotels_business: 'هۆتێلی کاری',
        hotels_boutique: 'هۆتێلی بوتیک',
        hotels_resort: 'کۆمەڵگەی هاوینەهەوار',
        alternative_vacation: 'کرێی پشوو',
        alternative_guest_houses: 'میوانخانە',
        alternative_hostels: 'هۆستێل',
        alternative_homestays: 'ماڵەمیوان',
        business_serviced_apartments: 'شوقەی خزمەتگوزاری',
        business_coliving: 'شوێنی ژیانی هاوبەش',
        business_conference: 'هۆتێلی کۆنفرانس',
        business_corporate: 'خانووی کۆمپانیا',
        accessible_wheelchair: 'گونجاو بۆ کورسی جوڵاو',
        accessible_family: 'گونجاو بۆ خێزان',
        accessible_pet: 'دۆستی ئاژەڵان',
        accessible_senior: 'گونجاو بۆ بەساڵاچوان',
        heritage_traditional: 'خانووی نەریتی',
        heritage_hotels: 'هۆتێلی کەلەپوری',
        heritage_religious: 'شوێنی مانەوەی ئایینی',
        heritage_eco_lodges: 'شوێنی حەوانەوەی ژینگەیی',

        shopping_malls: 'مۆڵەکان',
        shopping_department_stores: 'فرۆشگا گەورەکان',
        shopping_outlet_centers: 'ناوەندەکانی ئاوتلێت',
        shopping_retail_chains: 'زنجیرە فرۆشگاکان',
        shopping_souqs: 'بازاڕە Традиционные',
        shopping_farmers_markets: 'بازاڕی جوتیاران',
        shopping_night_markets: 'بازاڕە شه‌وانەکان',
        shopping_flea_markets: 'بازاڕی شتی بەکارهاتوو',
        shopping_handicrafts: 'کاری دەستی و هونەرمەندان',
        shopping_antiques: 'ئەنتیکە و کۆکراوەکان',
        shopping_local_products: 'بەرهەمە خۆماڵییەکان',
        shopping_artifacts: 'پارچە کلتورییەکان',
        shopping_tailoring: 'بەرگدرووی و چاککردن',
        shopping_electronics_repair: 'چاککردنی ئەلیکترۆنیات',
        shopping_shoe_repair: 'چاککردنی پێڵاو و چەرم',
        shopping_custom_orders: 'داواکاری تایبەت',
        shopping_eco_friendly: 'بەرهەمی ژینگەدۆستانە',
        shopping_local_producers: 'بەرهەمهێنەرە خۆماڵییەکان',
        shopping_secondhand: 'دەستی دوو و کۆن',
        shopping_fair_trade: 'بازرگانی دادپەروەرانە',

        historical_archaeological: 'شوێنەوارەکان',
        historical_monuments: 'شوێنەوارە مێژووییەکان',
        historical_unesco: 'میراتی یونسکۆ',
        historical_ruins: 'وێرانە کۆنەکان',
        museums_art: 'مۆزەخانەی هونەری',
        museums_historical: 'مۆزەخانەی مێژوویی',
        museums_science: 'زانست و تەکنەلۆژیا',
        museums_cultural_centers: 'ناوەندە کلتورییەکان',
        learning_libraries: 'کتێبخانەکان',
        learning_workshops: 'وۆرک شۆپ و وانەکان',
        learning_tours: 'گەشتی کلتوری',
        learning_educational_centers: 'ناوەندەکانی فێربوون',
        religious_mosques: 'مزگەوتەکان',
        religious_churches: 'کڵێساکان',
        religious_shrines: 'مەزارگەکان',
        religious_centers: 'ناوەندە ئایینییەکان',
        public_parks: 'پارک و باخچەکان',
        public_squares: 'گۆڕەپانە گشتییەکان',
        public_waterfronts: 'کەنارئاوەکان',
        // FIX: Renamed key to 'tourism_public_community_centers' to avoid duplicate key error.
        tourism_public_community_centers: 'ناوەندە کۆمەڵایەتییەکان',

        business_financial_banks: 'بانکەکان',
        business_financial_exchange: 'گۆڕینەوەی دراو',
        business_financial_atms: 'ئامێری پارەکێشان',
        business_financial_advisors: 'ڕاوێژکاری دارایی',
        business_comm_mobile: 'کۆمپانیاکانی مۆبایل',
        business_comm_internet: 'خزمەتگوزاری ئینتەرنێت',
        business_comm_postal: 'خزمەتگوزاری پۆستە',
        business_comm_printing: 'چاپ و کۆپیکردن',
        business_prof_legal: 'خزمەتگوزاری یاسایی',
        business_prof_accounting: 'ژمێریاری و باج',
        business_prof_centers: 'ناوەندەکانی کار',
        business_prof_coworking: 'شوێنی کاری هاوبەش',
        business_tech_it: 'پشتیوانی تەکنیکی',
        business_tech_engineering: 'خزمەتگوزاری ئەندازیاری',
        business_tech_repair: 'چاککردنی تەکنیکی',
        business_tech_digital: 'خزمەتگوزاری دیجیتاڵی',
        business_edu_tutoring: 'ناوەندی وانە تایبەتییەکان',
        business_edu_language: 'قوتابخانەی زمان',
        business_edu_vocational: 'ڕاهێنانی پیشەیی',
        business_edu_consultants: 'ڕاوێژکاری پەروەردەیی',
        
        health_medical_hospitals: 'نەخۆشخانەکان',
        health_medical_clinics: 'کلینیکەکان',
        health_medical_specialists: 'پسپۆڕان',
        health_medical_emergency: 'چاودێری فریاکەوتن',
        health_pharmacies_24hr: 'دەرمانخانەی ٢٤ کاتژمێری',
        health_pharmacies_traditional: 'پزیشکیی نەریتی',
        health_pharmacies_supplies: 'پێداویستی پزیشکی',
        health_pharmacies_prescription: 'خزمەتگوزارییەکانی دەرماننووسین',
        health_wellness_gyms: 'هۆڵی وەرزشی و سەنتەری لەشجوانی',
        health_wellness_yoga: 'یۆگا و تێڕامان',
        health_wellness_spas: 'سپا و ناوەندەکانی تەندروستی',
        health_wellness_sports: 'بنکە وەرزشییەکان',
        health_mental_counseling: 'خزمەتگوزاری ڕاوێژکاری',
        health_mental_support: 'گروپەکانی پشتیوانی',
        health_mental_therapy: 'ناوەندەکانی چارەسەری',
        health_mental_retreats: 'پشوودانی تەندروستی',
        health_family_pediatric: 'چاودێری منداڵان',
        health_family_womens: 'تەندروستی ئافرەتان',
        health_family_senior: 'چاودێری بەساڵاچووان',
        health_family_planning: 'ڕێکخستنی خێزان',
        
        transport_local_taxi: 'خزمەتگوزاری تاکسی',
        transport_local_rideshare: 'هاوبەشی گواستنەوە',
        transport_local_bus: 'پاسی گشتی',
        transport_local_metro: 'مترۆ و شەمەندەفەر',
        transport_vehicle_rentals: 'کرێی ئۆتۆمبێل',
        transport_vehicle_repair: 'چاککردنی ئۆتۆمبێل',
        transport_vehicle_fuel: 'بەنزینخانەکان',
        transport_vehicle_parking: 'پارکینگ',
        transport_travel_agencies: 'نووسینگەی گەشتیاری',
        transport_travel_airlines: 'نووسینگەی هێڵی ئاسمانی',
        transport_travel_bus_terminals: 'تێرمیناڵی پاس',
        transport_travel_train_stations: 'وێستگەی شەمەندەفەر',
        transport_accessible_wheelchair: 'گونجاو بۆ کورسی جوڵاو',
        transport_accessible_senior: 'گواستنەوەی بەساڵاچوان',
        transport_accessible_family: 'گواستنەوەی خێزانی',
        transport_accessible_special: 'خزمەتگوزاری پێداویستی تایبەت',
        transport_alternative_bike: 'کرێی پاسکیل',
        transport_alternative_walking: 'ڕێڕەوی پیاسە',
        transport_alternative_scooter: 'خزمەتگوزاری سکوتەر',
        transport_alternative_eco: 'گواستنەوەی ژینگەدۆست',

        public_gov_municipal: 'نووسینگەکانی شارەوانی',
        public_gov_police: 'بنکەکانی پۆلیس',
        public_gov_embassies: 'باڵیۆزخانە و کونسوڵخانەکان',
        public_gov_records: 'تۆمارە گشتییەکان',
        public_emergency_numbers: 'ژمارەکانی فریاکەوتن',
        public_emergency_police: 'بنکەکانی پۆلیس',
        public_emergency_fire: 'بەڕێوەبەرایەتییەکانی ئاگرکوژێنەوە',
        public_emergency_shelters: 'پەناگەکانی فریاکەوتن',
        public_community_centers: 'ناوەندە کۆمەڵایەتییەکان',
        public_community_religious: 'ناوەندە ئایینییەکان',
        public_community_ngos: 'ڕێکخراوە ناحکومییەکان و خێرخوازییەکان',
        public_community_volunteer: 'هەلەکانی خۆبەخشی',
        public_facilities_restrooms: 'توالێتە گشتییەکان',
        public_facilities_prayer: 'ژوورەکانی نوێژ',
        public_facilities_water: 'ئاوی خواردنەوە',
        public_facilities_wifi: 'ناوچەکانی وای فای گشتی',
        public_tourist_info: 'ناوەندەکانی زانیاری',
        public_tourist_guides: 'ڕێبەرە گەشتیارییەکان',
        public_tourist_translation: 'خزمەتگوزارییەکانی وەرگێڕان',
        public_tourist_visa: 'ڤیزا و کۆچ',
    },
    categoryModal: {
      title: 'گەڕان',
      allCategory: 'هەموو {category}'
    },
    featuredBusinesses: {
      title: "بازرگانی و شوێنە دیارەکان"
    },
    curatedEvents: {
      title: "ئیڤێنتی هەڵبژاردەی AI بۆ تۆ",
      description: "با زیرەکی دەستکردی ئێمە بیرۆکەی ناوازەی ئیڤێنت بەپێی حەزەکانت دروست بکات. کلیک لە دوگمەکە بکە بۆ دەستپێکردن!",
      generateButton: "دروستکردنی بیرۆکەی ئیڤێنت",
      generating: "زیرەکی دەستکرد بیردەکاتەوە...",
      error: "ببورە، هەڵەیەک ڕوویدا. تکایە دووبارە هەوڵبدەرەوە.",
      aiCurated: "AI هەڵیبژاردووە",
    },
    dealsMarketplace: {
        title: "بازاڕی داشکاندنەکان",
        claimed: "داواکراوە",
        expiresIn: "بەسەردەچێت لە",
        days: "رۆژ",
        hours: "کاتژمێر",
        minutes: "خولەک",
        seconds: "چرکە",
    },
    businessDirectory: {
        title: "لیستی بازرگانیەکان",
        searchPlaceholder: "بەپێی ناوی بازرگانی بگەڕێ...",
        filterByGovernorate: "فلتەر بەپێی پارێзگا",
        filterByCategory: "فلتەر بەپێی پۆل",
        filterByPrice: "نرخ",
        filterByRating: "هەڵسەنگاندن",
        sortBy: "ڕیزکردن بەپێی",
        allGovernorates: "هەموو پارێزگاکان",
        allCategories: "هەموو پۆلەکان",
        priceAll: "هەموو نرخێک",
        priceLow: "هەرزان",
        priceMid: "ناوەند",
        priceHigh: "گران",
        ratingAll: "هەموو هەڵسەنگاندنێک",
        sortDefault: "ئاسایی",
        sortNameAsc: "ناو (أ-ی)",
        sortRatingDesc: "هەڵسەنگاندن (بەرز-نزم)",
        resetFilters: "سڕینەوە",
        noResults: "هیچ بازرگانییەک نەدۆزرایەوە کە بگونجێت لەگەڵ پێوەرەکانی تۆ."
    },
    storyViewer: {
        close: "داخستنی پیشاندەری ستۆری",
        next: "ستۆری دواتر",
        previous: "ستۆری پێشوو"
    },
    cityNavigator: {
        title: "ڕێنمایی شار",
        description: "شارەکان بگەڕێ، شوێنە سەرنجڕاکێشەکان بدۆزەرەوە، و گەشتەکەت פּلان بکە بە بەکارهێنانی نەخشە کارلێکەرەکەمان.",
        searchPlaceholder: "بۆ شارێک یان شوێنێک بگەڕێ...",
        planJourneyButton: "پلانی گەشت"
    },
    accessibilityHub: {
        title: "ناوەندی دەستپێگەیشتن",
        description: "ئێمە پابەندین بەوەی کە عراق کۆمパス بۆ هەمووان بەردەست بێت. ئەزموونی خۆت لە خوارەوە بگونجێنە.",
        settingsTitle: "ڕێکخستنەکانی پیشاندان",
        fontSize: "قەبارەی فۆنت",
        fontSizeSmall: "بچووک",
        fontSizeDefault: "ئاسایی",
        fontSizeLarge: "گەورە",
        reduceMotion: "کەمکردنەوەی جوڵە",
        motionEnabled: "کاراکراو",
        motionReduced: "کەمکراوە",
        findInclusiveEventsTitle: "دۆزینەوەی شوێنە گشتگیرەکان",
        accessibleVenue: "شوێنی گونجاو"
    }
  }
};