import { Business, Category, City } from './types';

export const CITIES: City[] = ['Sulaymaniyah','Erbil','Baghdad','Basra','Mosul','Kirkuk','Duhok','Najaf'];

export const CATEGORIES: Category[] = [
  { id: 'restaurants', name: 'Restaurants', name_ar: 'مطاعم',   icon: '🍽️', color: 'bg-orange-100', accent: 'text-orange-600' },
  { id: 'cafes',       name: 'Cafes',       name_ar: 'مقاهي',   icon: '☕',  color: 'bg-amber-100',  accent: 'text-amber-600'  },
  { id: 'museums',     name: 'Museums',     name_ar: 'متاحف',   icon: '🏛️', color: 'bg-yellow-100', accent: 'text-yellow-700' },
  { id: 'hotels',      name: 'Hotels',      name_ar: 'فنادق',   icon: '🏨', color: 'bg-blue-100',   accent: 'text-blue-600'   },
  { id: 'hospitals',   name: 'Hospitals',   name_ar: 'مستشفيات',icon: '🏥', color: 'bg-red-100',    accent: 'text-red-600'    },
  { id: 'pharmacies',  name: 'Pharmacies',  name_ar: 'صيدليات', icon: '💊', color: 'bg-green-100',  accent: 'text-green-600'  },
  { id: 'banks',       name: 'Banks',       name_ar: 'بنوك',    icon: '🏦', color: 'bg-indigo-100', accent: 'text-indigo-600' },
  { id: 'parks',       name: 'Parks',       name_ar: 'حدائق',   icon: '🌳', color: 'bg-emerald-100',accent: 'text-emerald-600'},
  { id: 'shopping',    name: 'Shopping',    name_ar: 'تسوق',    icon: '🛍️', color: 'bg-pink-100',   accent: 'text-pink-600'   },
];

export const MOCK_BUSINESSES: Business[] = [
  { id:'r1', name:'Sarbast Restaurant', name_ar:'مطعم سربست', category_id:'restaurants', city:'Sulaymaniyah', address:'Salim St, near Azadi Square', address_ar:'شارع سالم، قرب ساحة آزادي', phone:'+964 770 111 2233', rating:4.8, review_count:312, lat:35.5605, lng:45.4329, is_sponsored:true, is_open:true, description:'Best grilled meats and Kurdish dishes in Sulaymaniyah.', description_ar:'أفضل المشاوي والأكلات الكردية في السليمانية.', created_at:'2024-01-01' },
  { id:'r2', name:'Layla BBQ House', name_ar:'بيت مشاوي ليلى', category_id:'restaurants', city:'Sulaymaniyah', address:'Kirkuk Rd, Bakhtiari District', address_ar:'طريق كركوك، حي بختياري', phone:'+964 770 222 3344', rating:4.5, review_count:178, lat:35.5550, lng:45.4400, is_sponsored:true, is_open:true, description:'Family-style restaurant with large outdoor seating.', description_ar:'مطعم عائلي مع مقاعد خارجية فسيحة.', created_at:'2024-02-01' },
  { id:'r3', name:'Miran Kebab', name_ar:'كباب ميران', category_id:'restaurants', city:'Sulaymaniyah', address:'Raparin St, City Center', address_ar:'شارع رابرين، مركز المدينة', phone:'+964 750 333 4455', rating:4.2, review_count:95, lat:35.5630, lng:45.4280, is_sponsored:false, is_open:true, description:'Quick and tasty kebab spot popular with locals.', description_ar:'مكان كباب سريع ولذيذ مشهور عند المحليين.', created_at:'2024-03-01' },
  { id:'c1', name:'Qaysari Café', name_ar:'مقهى قيصري', category_id:'cafes', city:'Sulaymaniyah', address:'Mawlawi St, Old City', address_ar:'شارع المولوي، المدينة القديمة', phone:'+964 770 555 6677', rating:4.9, review_count:430, lat:35.5580, lng:45.4350, is_sponsored:true, is_open:true, description:'Historic café serving traditional cardamom tea since 1962.', description_ar:'مقهى تاريخي يخدم الشاي بالهيل منذ 1962.', created_at:'2024-01-10' },
  { id:'c2', name:'Ster Coffee', name_ar:'ستير كوفي', category_id:'cafes', city:'Sulaymaniyah', address:'Italian Village', address_ar:'القرية الإيطالية', phone:'+964 750 666 7788', rating:4.7, review_count:289, lat:35.5700, lng:45.4200, is_sponsored:true, is_open:true, description:'Specialty coffee and pastries. Best flat white in the city.', description_ar:'قهوة مختصة وحلويات. أفضل فلات وايت في المدينة.', created_at:'2024-02-20' },
  { id:'c3', name:'Rooftop Lounge', name_ar:'مقهى الروفتوب', category_id:'cafes', city:'Sulaymaniyah', address:'Goizha Mountain Rd', address_ar:'طريق جبل كويژة', phone:'+964 770 777 8899', rating:4.4, review_count:156, lat:35.5800, lng:45.4150, is_sponsored:false, is_open:true, description:'Mountain-view café with hookah and snacks.', description_ar:'مقهى ذو إطلالة جبلية مع أرجيلة ومقبلات.', created_at:'2024-04-01' },
  { id:'m1', name:'Sulaymaniyah Museum', name_ar:'متحف السليمانية', category_id:'museums', city:'Sulaymaniyah', address:'Mawlawi St, City Center', address_ar:'شارع المولوي، مركز المدينة', phone:'+964 53 320 1234', rating:4.7, review_count:512, lat:35.5602, lng:45.4297, is_sponsored:true, is_open:true, description:'28,000+ artifacts including cuneiform tablets and Sumerian treasures.', description_ar:'أكثر من 28,000 قطعة أثرية منها ألواح مسمارية وكنوز سومرية.', created_at:'2024-01-01' },
  { id:'m2', name:'Amna Suraka Museum', name_ar:'متحف أمنة سوركة', category_id:'museums', city:'Sulaymaniyah', address:'Near Azadi Park', address_ar:'بالقرب من پارك ئازادي', phone:'+964 770 888 9900', rating:4.9, review_count:680, lat:35.5620, lng:45.4310, is_sponsored:false, is_open:true, description:'Former intelligence HQ turned memorial. Documents the Anfal genocide.', description_ar:'مقر الاستخبارات السابق المحوّل إلى نصب تذكاري.', created_at:'2024-01-01' },
  { id:'h1', name:'Sulaymaniyah Palace Hotel', name_ar:'فندق قصر السليمانية', category_id:'hotels', city:'Sulaymaniyah', address:'Salim St, City Center', address_ar:'شارع سالم، مركز المدينة', phone:'+964 53 330 5555', rating:4.6, review_count:341, lat:35.5610, lng:45.4320, is_sponsored:true, is_open:true, description:'5-star hotel with rooftop pool, spa, and free airport shuttle.', description_ar:'فندق خمس نجوم مع مسبح على السطح وسبا وخدمة نقل مجانية.', created_at:'2024-01-15' },
  { id:'h2', name:'Ashur Grand Hotel', name_ar:'فندق أشور الكبير', category_id:'hotels', city:'Sulaymaniyah', address:'Kirkuk Rd, Bakhtiari', address_ar:'طريق كركوك، بختياري', phone:'+964 770 999 0011', rating:4.2, review_count:198, lat:35.5560, lng:45.4390, is_sponsored:false, is_open:true, description:'Comfortable 4-star hotel near the bazaar.', description_ar:'فندق مريح 4 نجوم قريب من البازار.', created_at:'2024-02-10' },
  { id:'ho1', name:'Sulaymaniyah Teaching Hospital', name_ar:'مستشفى السليمانية التعليمي', category_id:'hospitals', city:'Sulaymaniyah', address:'Hospital St', address_ar:'شارع المستشفى', phone:'+964 53 320 8888', rating:4.1, review_count:876, lat:35.5590, lng:45.4260, is_sponsored:false, is_open:true, description:'Main public hospital. 24/7 emergency services.', description_ar:'المستشفى العام الرئيسي. خدمات طوارئ 24 ساعة.', created_at:'2024-01-01' },
  { id:'ho2', name:'Jwanro Private Hospital', name_ar:'مستشفى جوانرو الخاص', category_id:'hospitals', city:'Sulaymaniyah', address:'Italian Village Area', address_ar:'منطقة القرية الإيطالية', phone:'+964 770 111 3322', rating:4.7, review_count:423, lat:35.5710, lng:45.4180, is_sponsored:true, is_open:true, description:'Modern private hospital with specialist clinics.', description_ar:'مستشفى خاص حديث مع عيادات متخصصة.', created_at:'2024-03-01' },
  { id:'ph1', name:'Sina Pharmacy', name_ar:'صيدلية سينا', category_id:'pharmacies', city:'Sulaymaniyah', address:'Raparin St', address_ar:'شارع رابرين', phone:'+964 770 222 4433', rating:4.5, review_count:214, lat:35.5615, lng:45.4295, is_sponsored:true, is_open:true, description:'24-hour pharmacy with licensed pharmacist on duty.', description_ar:'صيدلية مفتوحة 24 ساعة مع صيدلاني معتمد.', created_at:'2024-01-05' },
  { id:'ph2', name:'Bayan Pharmacy', name_ar:'صيدلية بيان', category_id:'pharmacies', city:'Sulaymaniyah', address:'Mawlawi St', address_ar:'شارع المولوي', phone:'+964 750 333 5544', rating:4.3, review_count:130, lat:35.5575, lng:45.4340, is_sponsored:false, is_open:false, description:'Reliable pharmacy with home delivery.', description_ar:'صيدلية موثوقة مع توصيل للمنازل.', created_at:'2024-02-15' },
  { id:'b1', name:'Kurdistan International Bank', name_ar:'بنك كردستان الدولي', category_id:'banks', city:'Sulaymaniyah', address:'Salim St, Main Branch', address_ar:'شارع سالم، الفرع الرئيسي', phone:'+964 53 320 7777', rating:4.3, review_count:289, lat:35.5608, lng:45.4325, is_sponsored:true, is_open:true, description:'Full-service bank with forex and Western Union transfers.', description_ar:'بنك خدمات كاملة مع صرف عملات وويسترن يونيون.', created_at:'2024-01-01' },
  { id:'pk1', name:'Azadi Park', name_ar:'پارك ئازادي', category_id:'parks', city:'Sulaymaniyah', address:'City Center', address_ar:'مركز المدينة', phone:'', rating:4.6, review_count:1024, lat:35.5625, lng:45.4315, is_sponsored:false, is_open:true, description:'Central park with walking paths, playgrounds and fountains.', description_ar:'حديقة مركزية مع مسارات للمشي وملاعب ونوافير.', created_at:'2024-01-01' },
  { id:'pk2', name:'Goizha Resort Park', name_ar:'پارك منتجع كويژة', category_id:'parks', city:'Sulaymaniyah', address:'Goizha Mountain', address_ar:'جبل كويژة', phone:'+964 750 555 7766', rating:4.8, review_count:756, lat:35.5850, lng:45.4050, is_sponsored:true, is_open:true, description:'Mountain resort with cable car and stunning city views.', description_ar:'منتجع جبلي مع تلفريك وإطلالة رائعة على المدينة.', created_at:'2024-02-01' },
  { id:'s1', name:'Family Mall', name_ar:'فاميلي مول', category_id:'shopping', city:'Sulaymaniyah', address:'Airport Rd', address_ar:'طريق المطار', phone:'+964 53 330 9999', rating:4.5, review_count:1432, lat:35.5480, lng:45.4500, is_sponsored:true, is_open:true, description:'Largest mall with international brands, food court and cinema.', description_ar:'أكبر مول مع ماركات عالمية ومطعم وسينما.', created_at:'2024-01-01' },
  { id:'s2', name:'Qaysari Bazaar', name_ar:'بازار قيصري', category_id:'shopping', city:'Sulaymaniyah', address:'Old City', address_ar:'المدينة القديمة', phone:'', rating:4.7, review_count:2103, lat:35.5592, lng:45.4342, is_sponsored:false, is_open:true, description:'Historic bazaar. Best for spices, textiles and handicrafts.', description_ar:'بازار تاريخي. أفضل مكان للتوابل والمنسوجات والحرف اليدوية.', created_at:'2024-01-01' },
];
