import { City, Category, Business } from './types';

export const CITIES: City[] = ['Sulaymaniyah', 'Erbil', 'Baghdad', 'Basra', 'Mosul', 'Kirkuk', 'Duhok', 'Najaf'];

export const CATEGORIES: Category[] = [
  { id: 'restaurants', name: 'Restaurants', name_ar: 'مطاعم', icon: '🍽️', color: 'bg-orange-100', accent: 'text-orange-600' },
  { id: 'cafes', name: 'Cafés', name_ar: 'مقاهي', icon: '☕', color: 'bg-amber-100', accent: 'text-amber-600' },
  { id: 'museums', name: 'Museums', name_ar: 'متاحف', icon: '🏛️', color: 'bg-yellow-100', accent: 'text-yellow-600' },
  { id: 'hotels', name: 'Hotels', name_ar: 'فنادق', icon: '🏨', color: 'bg-blue-100', accent: 'text-blue-600' },
  { id: 'hospitals', name: 'Hospitals', name_ar: 'مستشفيات', icon: '🏥', color: 'bg-red-100', accent: 'text-red-600' },
  { id: 'pharmacies', name: 'Pharmacies', name_ar: 'صيدليات', icon: '💊', color: 'bg-green-100', accent: 'text-green-600' },
  { id: 'banks', name: 'Banks', name_ar: 'بنوك', icon: '🏦', color: 'bg-indigo-100', accent: 'text-indigo-600' },
  { id: 'parks', name: 'Parks', name_ar: 'حدائق', icon: '🌳', color: 'bg-emerald-100', accent: 'text-emerald-600' },
  { id: 'shopping', name: 'Shopping', name_ar: 'تسوق', icon: '🛍️', color: 'bg-pink-100', accent: 'text-pink-600' },
];

export const MOCK_BUSINESSES: Business[] = [
  {
    id: 'b1',
    name: 'Sarbast Restaurant',
    name_ar: 'مطعم سربست',
    category_id: 'restaurants',
    city: 'Sulaymaniyah',
    address: 'Salim Street, Sulaymaniyah',
    address_ar: 'شارع سالم، السليمانية',
    phone: '+964 770 111 2233',
    rating: 4.8,
    review_count: 342,
    lat: 35.5558,
    lng: 45.4351,
    is_sponsored: true,
    is_open: true,
    description: 'Traditional Kurdish cuisine with a modern twist. Famous for our kebabs and fresh bread.',
    description_ar: 'مأكولات كردية تقليدية بلمسة عصرية. مشهورون بالكباب والخبز الطازج.',
    created_at: '2023-01-15T10:00:00Z'
  },
  {
    id: 'b2',
    name: 'Layla BBQ House',
    name_ar: 'بيت مشاوي ليلى',
    category_id: 'restaurants',
    city: 'Sulaymaniyah',
    address: 'Sarchnar, Sulaymaniyah',
    address_ar: 'سرجنار، السليمانية',
    phone: '+964 770 222 3344',
    rating: 4.5,
    review_count: 215,
    lat: 35.5689,
    lng: 45.4122,
    is_sponsored: true,
    is_open: true,
    description: 'The best BBQ in town, located in the beautiful Sarchnar area.',
    description_ar: 'أفضل مشاوي في المدينة، يقع في منطقة سرجنار الجميلة.',
    created_at: '2023-02-20T12:30:00Z'
  },
  {
    id: 'b3',
    name: 'Miran Kebab',
    name_ar: 'كباب ميران',
    category_id: 'restaurants',
    city: 'Sulaymaniyah',
    address: 'Bazaar Area, Sulaymaniyah',
    address_ar: 'منطقة السوق، السليمانية',
    phone: '+964 770 333 4455',
    rating: 4.2,
    review_count: 512,
    lat: 35.5567,
    lng: 45.4432,
    is_sponsored: false,
    is_open: true,
    description: 'Authentic street-style kebab since 1990.',
    description_ar: 'كباب أصيل على طراز الشارع منذ عام 1990.',
    created_at: '2022-11-05T09:15:00Z'
  },
  {
    id: 'b4',
    name: 'Qaysari Café',
    name_ar: 'مقهى القيصرية',
    category_id: 'cafes',
    city: 'Sulaymaniyah',
    address: 'Grand Bazaar, Sulaymaniyah',
    address_ar: 'السوق الكبير، السليمانية',
    phone: '+964 770 444 5566',
    rating: 4.9,
    review_count: 890,
    lat: 35.5571,
    lng: 45.4421,
    is_sponsored: true,
    is_open: true,
    description: 'Historic café since 1962. Enjoy traditional tea and backgammon.',
    description_ar: 'مقهى تاريخي منذ عام 1962. استمتع بالشاي التقليدي ولعبة الطاولة.',
    created_at: '2021-05-10T08:00:00Z'
  },
  {
    id: 'b5',
    name: 'Ster Coffee',
    name_ar: 'ستير كوفي',
    category_id: 'cafes',
    city: 'Sulaymaniyah',
    address: 'Italian Village, Sulaymaniyah',
    address_ar: 'القرية الإيطالية، السليمانية',
    phone: '+964 770 555 6677',
    rating: 4.7,
    review_count: 156,
    lat: 35.5812,
    lng: 45.4210,
    is_sponsored: true,
    is_open: true,
    description: 'Specialty coffee, Italian Village. Premium roasted beans and quiet atmosphere.',
    description_ar: 'قهوة مختصة، القرية الإيطالية. حبوب محمصة فاخرة وجو هادئ.',
    created_at: '2023-08-12T07:30:00Z'
  },
  {
    id: 'b6',
    name: 'Rooftop Lounge',
    name_ar: 'لاونج السطح',
    category_id: 'cafes',
    city: 'Sulaymaniyah',
    address: 'Bakhtiari, Sulaymaniyah',
    address_ar: 'بختياري، السليمانية',
    phone: '+964 770 666 7788',
    rating: 4.4,
    review_count: 203,
    lat: 35.5610,
    lng: 45.4301,
    is_sponsored: false,
    is_open: true,
    description: 'Great views of the city with excellent coffee and desserts.',
    description_ar: 'إطلالات رائعة على المدينة مع قهوة وحلويات ممتازة.',
    created_at: '2023-04-01T16:00:00Z'
  },
  {
    id: 'b7',
    name: 'Sulaymaniyah Museum',
    name_ar: 'متحف السليمانية',
    category_id: 'museums',
    city: 'Sulaymaniyah',
    address: 'Salim Street, Sulaymaniyah',
    address_ar: 'شارع سالم، السليمانية',
    phone: '+964 770 777 8899',
    rating: 4.7,
    review_count: 645,
    lat: 35.5540,
    lng: 45.4360,
    is_sponsored: true,
    is_open: true,
    description: 'The second largest museum in Iraq. 28,000+ artifacts from prehistoric to Islamic periods.',
    description_ar: 'ثاني أكبر متحف في العراق. يضم أكثر من 28,000 قطعة أثرية من عصور ما قبل التاريخ إلى العصور الإسلامية.',
    created_at: '2020-01-01T09:00:00Z'
  },
  {
    id: 'b8',
    name: 'Amna Suraka Museum',
    name_ar: 'متحف أمنة سوركة',
    category_id: 'museums',
    city: 'Sulaymaniyah',
    address: 'Mawlawi Street, Sulaymaniyah',
    address_ar: 'شارع مولوي، السليمانية',
    phone: '+964 770 888 9900',
    rating: 4.9,
    review_count: 1205,
    lat: 35.5601,
    lng: 45.4312,
    is_sponsored: false,
    is_open: true,
    description: 'Anfal memorial and museum of national history. A must-visit for understanding the region.',
    description_ar: 'نصب تذكاري للأنفال ومتحف للتاريخ الوطني. زيارة لا بد منها لفهم المنطقة.',
    created_at: '2020-02-01T09:00:00Z'
  },
  {
    id: 'b9',
    name: 'Sulaymaniyah Palace Hotel',
    name_ar: 'فندق قصر السليمانية',
    category_id: 'hotels',
    city: 'Sulaymaniyah',
    address: 'Salim Street, Sulaymaniyah',
    address_ar: 'شارع سالم، السليمانية',
    phone: '+964 770 999 0011',
    rating: 4.6,
    review_count: 432,
    lat: 35.5550,
    lng: 45.4355,
    is_sponsored: true,
    is_open: true,
    description: '5-star luxury hotel with a rooftop pool, spa, and fine dining restaurants.',
    description_ar: 'فندق فاخر 5 نجوم يضم مسبحاً على السطح ومنتجعاً صحياً ومطاعم راقية.',
    created_at: '2021-10-15T14:00:00Z'
  },
  {
    id: 'b10',
    name: 'Ashur Grand Hotel',
    name_ar: 'فندق آشور جراند',
    category_id: 'hotels',
    city: 'Sulaymaniyah',
    address: 'Sarchnar, Sulaymaniyah',
    address_ar: 'سرجنار، السليمانية',
    phone: '+964 770 000 1122',
    rating: 4.2,
    review_count: 189,
    lat: 35.5695,
    lng: 45.4110,
    is_sponsored: false,
    is_open: true,
    description: 'Comfortable stay near the Sarchnar resort area with beautiful gardens.',
    description_ar: 'إقامة مريحة بالقرب من منطقة منتجع سرجنار مع حدائق جميلة.',
    created_at: '2022-03-22T11:00:00Z'
  },
  {
    id: 'b11',
    name: 'Jwanro Private Hospital',
    name_ar: 'مستشفى جوانرو الأهلي',
    category_id: 'hospitals',
    city: 'Sulaymaniyah',
    address: 'Ibrahim Pasha, Sulaymaniyah',
    address_ar: 'إبراهيم باشا، السليمانية',
    phone: '+964 771 111 2233',
    rating: 4.7,
    review_count: 85,
    lat: 35.5620,
    lng: 45.4250,
    is_sponsored: true,
    is_open: true,
    description: 'Modern medical facilities with top specialists in various fields.',
    description_ar: 'مرافق طبية حديثة مع كبار المتخصصين في مختلف المجالات.',
    created_at: '2021-07-10T08:00:00Z'
  },
  {
    id: 'b12',
    name: 'Sulaymaniyah Teaching Hospital',
    name_ar: 'مستشفى السليمانية التعليمي',
    category_id: 'hospitals',
    city: 'Sulaymaniyah',
    address: 'Hospital Road, Sulaymaniyah',
    address_ar: 'طريق المستشفى، السليمانية',
    phone: '+964 771 222 3344',
    rating: 4.1,
    review_count: 320,
    lat: 35.5580,
    lng: 45.4380,
    is_sponsored: false,
    is_open: true,
    description: 'Main public hospital. 24/7 emergency services available.',
    description_ar: 'المستشفى العام الرئيسي. خدمات الطوارئ متاحة على مدار 24 ساعة.',
    created_at: '2020-01-01T00:00:00Z'
  },
  {
    id: 'b13',
    name: 'Sina Pharmacy',
    name_ar: 'صيدلية سينا',
    category_id: 'pharmacies',
    city: 'Sulaymaniyah',
    address: 'Doctors Street, Sulaymaniyah',
    address_ar: 'شارع الأطباء، السليمانية',
    phone: '+964 771 333 4455',
    rating: 4.5,
    review_count: 112,
    lat: 35.5590,
    lng: 45.4390,
    is_sponsored: true,
    is_open: true,
    description: '24 hours open. Wide range of medicines and cosmetics.',
    description_ar: 'مفتوح 24 ساعة. مجموعة واسعة من الأدوية ومستحضرات التجميل.',
    created_at: '2022-05-18T09:00:00Z'
  },
  {
    id: 'b14',
    name: 'Bayan Pharmacy',
    name_ar: 'صيدلية بيان',
    category_id: 'pharmacies',
    city: 'Sulaymaniyah',
    address: 'Bakhtiari, Sulaymaniyah',
    address_ar: 'بختياري، السليمانية',
    phone: '+964 771 444 5566',
    rating: 4.3,
    review_count: 67,
    lat: 35.5615,
    lng: 45.4290,
    is_sponsored: false,
    is_open: false,
    description: 'Local pharmacy providing prescription and over-the-counter medicines.',
    description_ar: 'صيدلية محلية توفر الأدوية بوصفة طبية وبدون وصفة طبية.',
    created_at: '2022-08-20T10:00:00Z'
  },
  {
    id: 'b15',
    name: 'Kurdistan International Bank',
    name_ar: 'مصرف كردستان الدولي',
    category_id: 'banks',
    city: 'Sulaymaniyah',
    address: 'Salim Street, Sulaymaniyah',
    address_ar: 'شارع سالم، السليمانية',
    phone: '+964 771 555 6677',
    rating: 4.3,
    review_count: 45,
    lat: 35.5545,
    lng: 45.4358,
    is_sponsored: true,
    is_open: true,
    description: 'Full banking services, ATMs, and international transfers.',
    description_ar: 'خدمات مصرفية كاملة وأجهزة صراف آلي وتحويلات دولية.',
    created_at: '2021-11-11T08:30:00Z'
  },
  {
    id: 'b16',
    name: 'Azadi Park',
    name_ar: 'بارك آزادي',
    category_id: 'parks',
    city: 'Sulaymaniyah',
    address: 'Azadi, Sulaymaniyah',
    address_ar: 'آزادي، السليمانية',
    phone: '',
    rating: 4.6,
    review_count: 980,
    lat: 35.5650,
    lng: 45.4320,
    is_sponsored: false,
    is_open: true,
    description: 'Large public park with walking trails, lakes, and children play areas.',
    description_ar: 'حديقة عامة كبيرة تضم مسارات للمشي وبحيرات ومناطق لعب للأطفال.',
    created_at: '2020-05-01T06:00:00Z'
  },
  {
    id: 'b17',
    name: 'Goizha Resort Park',
    name_ar: 'منتزه جبل كويزة',
    category_id: 'parks',
    city: 'Sulaymaniyah',
    address: 'Mount Goizha, Sulaymaniyah',
    address_ar: 'جبل كويزة، السليمانية',
    phone: '+964 771 666 7788',
    rating: 4.8,
    review_count: 750,
    lat: 35.5750,
    lng: 45.4500,
    is_sponsored: true,
    is_open: true,
    description: 'Beautiful mountain park with a cable car and panoramic views of the city.',
    description_ar: 'حديقة جبلية جميلة مع تلفريك وإطلالات بانورامية على المدينة.',
    created_at: '2021-04-15T10:00:00Z'
  },
  {
    id: 'b18',
    name: 'Family Mall',
    name_ar: 'فاميلي مول',
    category_id: 'shopping',
    city: 'Sulaymaniyah',
    address: 'Baban Road, Sulaymaniyah',
    address_ar: 'طريق بابان، السليمانية',
    phone: '+964 771 777 8899',
    rating: 4.5,
    review_count: 1500,
    lat: 35.5700,
    lng: 45.4200,
    is_sponsored: true,
    is_open: true,
    description: 'Largest shopping mall in the city. Features a cinema, food court, and international brands.',
    description_ar: 'أكبر مركز تسوق في المدينة. يضم سينما وقاعة طعام وعلامات تجارية دولية.',
    created_at: '2022-01-10T10:00:00Z'
  },
  {
    id: 'b19',
    name: 'Qaysari Bazaar',
    name_ar: 'سوق القيصرية',
    category_id: 'shopping',
    city: 'Sulaymaniyah',
    address: 'City Center, Sulaymaniyah',
    address_ar: 'وسط المدينة، السليمانية',
    phone: '',
    rating: 4.7,
    review_count: 820,
    lat: 35.5570,
    lng: 45.4425,
    is_sponsored: false,
    is_open: true,
    description: 'Historic bazaar offering traditional clothes, spices, and local goods.',
    description_ar: 'سوق تاريخي يقدم الملابس التقليدية والتوابل والسلع المحلية.',
    created_at: '2020-01-01T08:00:00Z'
  }
];
